### PR TITLE
added crio byte for peer to peer file sharing

### PR DESCRIPTION
**Pull request by sainimohit23**
Added crio byte for p2p file sharing.

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by Kevinpaulose05** [comment]
> Added crio byte for p2p file sharing.
> 
> * [] Added activities for learners
> * [] Didn't give the solutions to the added activities straight away
> * [] Followed a LearnByDoing approach
> * [] Clean and well documented code (if source code files are involved)
> * [x]  Added images for better understanding if deemed necessary

Pls make a PR after completing the above criterion. Avoid incomplete PRs

**Comment by sainimohit23** [comment]
@Kevinpaulose05 this byte is about a Networking protocol. I don't think I can add any activity or code to this. If you have any idea, please suggest. I would be more than happy to work on it. I also referred to the OS micro bytes and I didn't saw any activity or code or anything related to LearnByDoing in that repository. 

My next byte will be related to the socket programming. Maybe I will be able to include some activities and code in there.

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 this byte is about a Networking protocol. I don't think I can add any activity or code to this. If you have any idea, please suggest. I would be more than happy to work on it. I also referred to the OS micro bytes and I didn't saw any activity or code or anything related to LearnByDoing in that repository.
> 
> My next byte will be related to the socket programming. Maybe I will be able to include some activities and code in there.

Get back to u by evening?

**Comment by sainimohit23** [comment]
@Kevinpaulose05 Ok no issues.

**Comment by YourAKShaw** [comment]
> @Kevinpaulose05 this byte is about a Networking protocol. I don't think I can add any activity or code to this. If you have any idea, please suggest. I would be more than happy to work on it. I also referred to the OS micro bytes and I didn't saw any activity or code or anything related to LearnByDoing in that repository.
> 
> My next byte will be related to the socket programming. Maybe I will be able to include some activities and code in there.

@sainimohit23 actually **the OS ones are currently just draft sub-folders** which need contributors to work on. Till we get back at you, you can raise an issue using the proper issue template for adding a MicroByte, that might help you think clearly about your approach. You can refer [this](https://github.com/Crio-Bytes/Miscellaneous/issues/3) for a clear picture.

**Comment by sainimohit23** [comment]
@Kevinpaulose05 please review.

**Review by sudhanshutiwari264 — APPROVED** [review]
Looks good to me!🎉

**Review by Kevinpaulose05 — COMMENTED** [review]
Pls check up on my comment

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
Thing is P2P file sharing has a lot more to what u have done, like APPN,APPC,etc. What you have done is a 5 min read. This won't help anyone.I agree the topic is more theoretical than practical. But for such a topic numerous questions arise. Some of the critical questions should be given by you with a detailed solution. 
**NOTE:** use details markdown like <details><summary>text</summary>hidden_text(solution)</details> for hiding solutions. 
Pls provide more theory and apllications. Loading a torrent file is child's play and u should not expect to leave P2P sharing at that point. 
Please don't feel intimidated from this but it is what it is @sainimohit23 . Try to come up with some more concepts.
Maybe build ur own P2P sharing application like [this](https://medium.com/@amannagpal4/how-to-create-your-own-decentralized-file-sharing-service-using-python-2e00005bdc4a).
Feel free to discuss more.
Also please let us know if u have completed the official hacktoberfest challenge or still need a PR count for that through this.
Cheers

**Comment by sainimohit23** [comment]
@Kevinpaulose05 @Ak-Shaw @sudhanshutiwari264 when bytes was introduced I completed the OOM and Stack & Heap. From what I remember those were also 5-10 min read and were very basic(like an excerpt from Galvin). I understand that the structure of the byte might not be that great and I can work on that. But, do you really think that anyone would be interested in APPN, APPC?

By suggesting me to build a full P2P application you are asking me to contribute a full-fledged micro-experience, not a byte. Not gonna happen. I had plans to build bytes for topics like socket programming, DHCP, working of a router, etc. I was doing this because I was really interested in this project found it really helpful to document some stuff(I already have surplus PRs). Closing.

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 @Ak-Shaw @sudhanshutiwari264 when bytes was introduced I completed the OOM and Stack & Heap. From what I remember those were also 5-10 min read and were very basic(like an excerpt from Galvin). I understand that the structure of the byte might not be that great and I can work on that. But, do you really think that anyone would be interested in APPN, APPC?
> 
> By suggesting me to build a full P2P application you are asking me to contribute a full-fledged micro-experience, not a byte. Not gonna happen. I had plans to build bytes for topics like socket programming, DHCP, working of a router, etc. I was doing this because I was really interested in this project found it really helpful to document some stuff(I already have surplus PRs for hacktoberfest). Closing.

Then its fine. U can work on all such topics in which u r interested in. No need for an app, i agree. Create different issues and different Prs to each. a well documented contribution is what we r looking for. A microbyte should typically be at max of 1hr but also not too small. Just imagine if we would start ,erging small microbytes the quality of content would be diluted. If I have offended u in any way i apologize ofr it. Going through ur github profile I have understood u r a serious programmer/developer and have potential to contribute good stuff. The PR u just submitted did not reflect it. So it was my duty to gauge how genuine it was. 

Some of the PRs we were really appreciative of were [this](https://github.com/Crio-Bytes/Networking/tree/main/traceroute) and [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant). Be unique in your own way and we will showcase yours too just like this. We need to be cautious of the quality/originality of the PRs so that the repos aren't spammed.

Now a couple of suggestions u can follow:
1. Add some more content, just to keep the contributors more engaged with ur microbyte. Any interesting content related to P2P sharing. 
2.Immediate thing to do: Hide ur solution. It give a better appeal to ur microbyte.
3.Keep contributing like this one and maybe we can have a mini version of Galvin here. 

Ur contribution is always valued and appreciated.

Feel free to discuss more on this if needed

**Pull request closed without merging**
