### PR TITLE
Add traceroute MicroByte

### PR DESCRIPTION
**Pull request by vrajashkr**
### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by Kevinpaulose05 — APPROVED** [review]
Awesome work @DarkAEther . I am quite impressed with ur microbyte. can u pls mention what contributors can contribute t, only if any scope for it exists.
Urs will be merged after another advocate approves it. 
Kudos!

**Comment by vrajashkr** [comment]
@Kevinpaulose05 Thanks for the feedback! Should I mention possible contribution scopes in the README (maybe at the end in a contribution ideas section) ?

**Comment by YourAKShaw** [comment]
@DarkAEther You can raise issues once the PR gets merged.

**Review by YourAKShaw — APPROVED** [review]
@DarkAEther I'm impressed. This is some interactive premium content! :rocket: Thank you for your contributions. :heart_decoration:

**Comment by Kevinpaulose05** [comment]
Next thing that you should do @DarkAEther is showcase this PR on microbyte-showcase channel.

Kindly follow the below mentioned format for ur msg-

All creators who have their PRs accepted and merged can show off their contribution in the microbyte-showcase channel. This will help the other participants by keeping them updated. Also, kindly refrain from spamming the channel with every minor contribution you may make. Please give a brief compiled overview of your contribution.

**Template (Kindly stick to this format):**
Title of your project #(repo-topic)
A brief overview of your project (not more than 3-5 lines). GITHUB LINK of byte must be provided. In the end of this briefing use #(languages), #(software), #(skills) tags.
Actively looking for contributors (both learners and creators). **Please raise an issue first and then submit your PRs to that issue only (either after or before assigning the issue to you).** Also, you can suggest how they can contribute.

**Template example:**
Concurrency #OS
Brief description. [GITHUB LINK]. #C++ #Python #Shell #Django
Actively looking for contributors. Learners can to this _ and creators can do this __. Please raise an issue first and then submit your PRs to that issue only.
#learnbydoing #microbyte-showcase

Needless to say keep contributing!!

**Comment by sudhanshutiwari264** [comment]
@DarkAEther Nice work and it's just like a premium microbyte !👍👩‍💻

**Comment by archithdwij** [comment]
@DarkAEther Very well done! The team was totally impressed with your contribution. Looking forward to more contributions like these! :)

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @DarkAEther  for code doc ideas content

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @Kevinpaulose05 for review and eventOrganizing

**Pull request merged**
